### ISSUE TITLE
我在使用功能时遇到的问题+修改建议

### ISSUE THREAD

**Issue by YXH-YXH** [GuJin/TimeTable#1]
1.我这里的课程 有三个信息，课程名，课程教师，课程地点   一个课程有多个地点，该怎么添加课程？
2.启用单双周的逻辑 有些 麻烦，部分课程有单双周，部分课程没有单双周，当启用单双周时，就无法选择全周，是否将启用单双周 更改为 三个选项（单周，双周，全周）
3.通过二维码扫描课程 不是太会用，（我该怎么找到我的课程的二维码？  可能学校不支持，是否可以提供 Excel表格等方式导入？） 
4.是否可以单周，双周课程都显示在同一个 表格中，只是非本周的课程是灰色的？
5.部分课程是小课，是常规的一半。

6.不知为什么有时打开有 课程会全部挤到一起，这是什么bug？
8.晚上的课程无法完整显示，（会和下午课程挤到一起），点击晚上的空白课程，会显示 当天下午的课程详情

非常感谢您提供的宝贵程序！

**Comment by GuJin** [comment]
1.最初设计的时候是没有授课教师这一属性的，课程名称和课程地点组成一个课程，如果是多个地点，需要先生成多个对应的课程。
2.在2.1.2版本已优化，非常感谢反馈。
3.二维码来自他人的分享。其他导入方式截止到现在（2018-03-07）我还没有什么好的想法。
4.我担心在阳光强烈或者快速看一眼的情况下，可能发生看错的情况，还要再考虑。
5.存在小课A上完后紧接着上小课B的情况么？否则的话看起来下了课直接走就行了。
6.在2.1.2版本已修复。
7.第七个问题被吃了？？？
8.在2.1.2版本已修复。

感谢反馈。

**Comment by GuJin** [comment]
1. 最初设计的时候是没有授课教师这一属性的，课程名称和课程地点组成一个课程，如果是多个地点，需要先生成多个对应的课程。
2. 在 2.1.2 版本已优化，非常感谢反馈。
3. 二维码来自他人的分享。其他导入方式截止到目前（2018-03-07）我还没有什么好的想法。
4. 我担心在阳光强烈或者快速看一眼的情况下，可能发生看错的情况，还要再考虑。
5. 存在小课A上完后紧接着上小课B的情况么？否则的话看起来下了课直接走就行了。
6. 在 2.1.2 版本已修复。
7. 第七个问题被吃了？？？
8. 在 2.1.2 版本已修复。

感谢反馈。

**Comment by YXH-YXH** [comment]
老实的说，我使用此软件 时，光添加课程就添加了两个小时，这在添加课程方面感到特别的不方便；
关于1
我现在的确是 如此操作的，只是，操作过于麻烦。
关于3
可否 设置一个从学校教务系统导入课程？
或者提供一个 可以从电脑打开的表格，从电脑中将课程填写到表格中，生成二维码，让后用手机扫描？
（二维码 来自他人的分享是指  通过 本软件 生成的二维码专用吗？）
关于4
非常期待 您能 将非本周的课程 也显示出来， （此时还可能 会有2种情况，前半段时间是 课程A，后半段时间是课程B，    或AB单双周出现）
关于5
我想说 的确存在， 还存在 两节课（整个上午或下午  只上一节课的情况）
关于7
失误，抱歉。

现在 我已经 更新到了2.1.3版本，给你好评！

**Comment by GuJin** [comment]
1. 其实可以做到添加课程后，再设置课程地点，再给地点设置上课时间，但是手机屏幕没有那么大地方，我也在寻找更为高效的课程输入方式。
2. 教务系统或 Excel 导入因为最近上班忙近期内估计无法实现。
3. 二维码是软件内点击分享课表时生成的二维码。
4. 我会考虑，或者说是等有相同需求的人多了之后我会重新考虑，毕竟软件是给很多人使用的，肯定不能一个人提出需求我就做出改变。所以也请不要抱有非常高的期望，以免会有失望。
5. 小课的情况我会考虑，但什么时候更新这个不好说。

非常感谢。
